# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_todo_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='place',
            field=models.IntegerField(null=True),
        ),
    ]
